names = [
    "1. Sleep In",
    "2. Monkey Trouble",
    "3. String Times",
    "4. Front Times",
    "5. String Bits",
    "6. Caught Speeding",
    "7. FizzBuzz",
    "8. Tea Party",
    "9. Black Jack",
    "10.Lone Sum",
    "11. First Last 6",
    "12. Has 23",
    "13. Fix 23 [always red]",
    "14. Count YZ",
    "15. End Other",
    "16. Star Out",
    "17. Get Sandwich",
    "18. Can Balance",
    "19. Count Clumps",
    "20. Evenly Spaced",
    "21. Count Evens",
    "22. Count Hi",
    "23. No 14",
    "24. Either 24",
    "25. Make Chocolate",
    "26. Lucky Sum",
    "27. Max Block",
    "28. Linear In",
    "29. Count Triple",
    "30. Same Ends",
    "31. Let Them Eat Cake"
];
